VERSION 4.00
Begin VB.Form Form2 
   Caption         =   "Form2"
   ClientHeight    =   4140
   ClientLeft      =   2025
   ClientTop       =   8550
   ClientWidth     =   6690
   Height          =   4545
   Left            =   1965
   LinkTopic       =   "Form2"
   ScaleHeight     =   4140
   ScaleWidth      =   6690
   Top             =   8205
   Width           =   6810
End
Attribute VB_Name = "Form2"
Attribute VB_Creatable = False
Attribute VB_Exposed = False
